site_name: SwipeTerminal

theme:
    name: material

nav:
- About: index.md

- Installation: installation.md

- Manual:
    - Rendering: rendering.md
    - Mathematics: mathematics.md
    - Physics: physics.md
    - UI: ui.md
    - Audio: audio.md
    - Input: input.md
